"""added ondelete in reservation fk

Revision ID: e42bc87ec267
Revises: 967c75a4ac02
Create Date: 2025-04-15 12:33:05.396036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42bc87ec267'
down_revision: Union[str, None] = '967c75a4ac02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reservations_table_id_fkey', 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'tables', ['table_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key('reservations_table_id_fkey', 'reservations', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###
